# Application Configuration
spring:
  application:
    name: lms
  
  # Database Configuration - Using PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/sms
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  
  h2:
    console:
      enabled: false
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Server Configuration
server:
  port: 8080

# Security Configuration
jwt:
  secret: Q3RfO8dYHj1h7zGQkFbT1qR7f3pLrHHy1q9q0pBtTz9rjFzZc4K0xS0zV+zM6kS9tR4dU3Pj3G1V2Q8Bz6xq5w==
  expiration: 86400000
  refresh-expiration: 604800000

# Logging Configuration
logging:
  level:
    com.utc.lms: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# CORS Configuration
cors:
  allowed-origins: 
    - http://localhost:3000
    - http://localhost:8080
  allowed-methods: 
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"
  allow-credentials: true
